server:
  port: 8010

spring:
  application:
    name: order-service

ksqldbprops:
  host: localhost
  port: 8088
  ordersStream: orders_stream
  customersTable: customers_table
  ordersEnrichedStream: orders_enriched_stream
  fraudOrderTable: fraud_order

kafkaprops:
  bootstrapServers: localhost:9092
  schemaRegistryUrl: http://localhost:8081
  autoOffsetReset: earliest
  processingGuarantee: at_least_once
  commitInterval: 1
  sessionTimeout: 30000
  stateDir: "/tmp/kafka-streams-orders"
  appId: ${spring.application.name}
  enableIdempotence: false
  acks: all
  clientId: ${spring.application.name}
  enableExactlyOnce: false

application:
  host: localhost
  port: ${server.port}

topicprops:
  ordersTopic: orders.v1
  ordersEnrichedTopic: orders-enriched.v1
  inventoryTopic: warehouse-inventory.v1
  orderValidationTopic: order-validations.v1
  paymentsTopic: payments.v1
  customersTopic: customers.v1
  platinumTopic: platinum
  goldTopic: gold
  silverTopic: silver
  bronzeTopic: bronze
  schemaRegistryUrl: http://localhost:8081
  partitions: 3
  replication: 1