server:
  port: 8050

spring:
  application:
    name: email-service
  kafka:
    bootstrap-servers: ${kafkaprops.bootstrapServers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bootstrap-servers: ${kafkaprops.bootstrapServers}
      acks: ${kafkaprops.acks}
      client-id: ${kafkaprops.clientId}
      properties:
        enable.idempotence: ${kafkaprops.enableIdempotence}
        schema.registry.url: ${kafkaprops.schemaRegistryUrl}
        auto.register.schemas: false
    streams:
      application-id: ${spring.application.name}
      bootstrap-servers: ${kafkaprops.bootstrapServers}
      state-dir: ${kafkaprops.stateDir}
      properties:
        schema.registry.url: ${kafkaprops.schemaRegistryUrl}



kafkaprops:
  bootstrapServers: localhost:9092
  schemaRegistryUrl: http://localhost:8081
  autoOffsetReset: earliest
  processingGuarantee: at_least_once
  commitInterval: 1
  sessionTimeout: 30000
  stateDir: "/tmp/kafka-streams-email"
  appId: ${spring.application.name}
  enableIdempotence: false
  acks: all
  clientId: ${spring.application.name}
  enableExactlyOnce: false


application:
  host: localhost
  port: ${server.port}

topicprops:
  ordersTopic: orders.v1
  ordersEnrichedTopic: orders-enriched.v1
  inventoryTopic: warehouse-inventory.v1
  orderValidationTopic: order-validations.v1
  paymentsTopic: payments.v1
  customersTopic: customers.v1
  platinumTopic: platinum
  goldTopic: gold
  silverTopic: silver
  bronzeTopic: bronze
  schemaRegistryUrl: http://localhost:8081
  partitions: 3
  replication: 1