kafkaprops:
  bootstrapServers: kafka:29092
  schemaRegistryUrl: http://schema-registry:8081
  autoOffsetReset: earliest
  processingGuarantee: at_least_once
  commitInterval: 1
  sessionTimeout: 30000
  stateDir: "/tmp/kafka-streams-email"
  appId: ${spring.application.name}
  enableIdempotence: false
  acks: all
  clientId: ${spring.application.name}
  enableExactlyOnce: false

topicprops:
  ordersTopic: orders.v1
  ordersEnrichedTopic: orders-enriched.v1
  inventoryTopic: warehouse-inventory.v1
  orderValidationTopic: order-validations.v1
  paymentsTopic: payments.v1
  customersTopic: customers
  platinumTopic: platinum
  goldTopic: gold
  silverTopic: silver
  bronzeTopic: bronze
  schemaRegistryUrl: http://schema-registry:8081
  partitions: 3
  replication: 1